### ISSUE TITLE
Update for 0.4 ?

### ISSUE THREAD

**Issue by r-lipton** [mbaske/ml-agents-hyperparams#2]
Hello,
Do you plan to update to the 0.4 version ? 

Thanks

**Comment by mbaske** [comment]
Hi @r-lipton, 
Unfortunately, I couldn't get my code working with ml-agents' updated communication model (grpc) yet. <del>Fixing this appears to be a bit beyond my python skills right now... I'll try to further isolate the problem and maybe create a (non-working) v0.4 branch for people to take a crack at it.</del>

**Comment by mbaske** [comment]
OK, there's a new version supporting ml-agents v0.4.
I've replaced futures.ProcessPoolExecutor with subprocess.Popen. Training data is exchanged through json files.

**Comment by r-lipton** [comment]
Thank you!
