### ISSUE TITLE
no SIGUSR1

### ISSUE THREAD

**Issue by xiaozhuzhuzhu** [mbaske/ml-agents-hyperparams#3]
The system installed on my computer is a windows system, so 'SIGUSR1' cannot be used. The error is AttributeError: module 'signal' has no attribute 'SIGUSR1'. Can I use SIGTEM instead of it? Or should I modify the code? So how should the code be modified? In addition, has your tennis parameter adjusted, can you tell me how much it should be set?

**Comment by mbaske** [comment]
Hi @xiaozhuzhuzhu, 
As far as I know, UNIX signals are not supported on Windows. I recommend you use the new version for m-agents v0.4 which doesn't rely on signals.
In both versions, I removed the --train parameter for launching tune.py because it's redundant.

**Comment by xiaozhuzhuzhu** [comment]
@mbaske Thank you very much! I will have a try to use  the  new version for ml-agent v0.4.
