### ISSUE TITLE
addition value_estiamte and other curves

### ISSUE THREAD

**Issue by xiaozhuzhuzhu** [mbaske/ml-agents-hyperparams#5]
hi
Have you considered updating the curve with a value_estimate recently? Because my value_estimate curve always goes down and the opposite is said in the document of ml-agents-master.

**Comment by mbaske** [comment]
Yes, value estimates should increase together with cumulative rewards as the agent learns. However, if and how fast it learns depends on the chosen hyperparameters. My code doesn't affect those values/curves directly, only indirectly through the hyperparameter settings.
